import React, { useState, useEffect } from 'react';
import { FileText, Download, TrendingUp, Users, Calendar, Activity } from 'lucide-react';
import { motion } from 'framer-motion';
import api from '../services/api';
import { jsPDF } from 'jspdf';

const Reports = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      console.log('Fetching reports from API...');
      const res = await api.get('/reports');
      console.log('Reports response:', res.data);
      setReports(res.data);
    } catch (err) {
      console.error("Error fetching reports", err);
      setError(err.response?.data?.message || err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = (report) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(33, 150, 243); // Primary color
    doc.text('HOSPITAL MANAGEMENT SYSTEM', 105, 20, { align: 'center' });
    
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('MEDICAL REPORT', 105, 30, { align: 'center' });
    
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 35, 190, 35);
    
    // Report Info
    doc.setFontSize(12);
    doc.text(`Report ID: ${report._id}`, 20, 50);
    doc.text(`Date: ${new Date(report.date).toLocaleDateString()}`, 20, 60);
    doc.text(`Type: ${report.title}`, 20, 70);
    doc.text(`Category: ${report.category}`, 20, 80);
    
    // Patient Info
    doc.setFont(undefined, 'bold');
    doc.text('Patient Information:', 20, 100);
    doc.setFont(undefined, 'normal');
    doc.text(`Name: ${report.patient?.name || 'N/A'}`, 20, 110);
    doc.text(`Patient ID: ${report.patient?._id || 'N/A'}`, 20, 120);
    
    // Summary
    doc.setFont(undefined, 'bold');
    doc.text('Clinical Summary:', 20, 140);
    doc.setFont(undefined, 'normal');
    const splitText = doc.splitTextToSize(
      report.summary || "This is a dummy medical report for demonstration purposes. The results indicate normal levels across all tested parameters. Further consultation with a specialist is recommended if symptoms persist.",
      170
    );
    doc.text(splitText, 20, 150);
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Hospital Management System Auto-Report Utility', 105, 280, { align: 'center' });
    
    doc.save(`${report.title.replace(/\s+/g, '_')}_${report.patient?.name.replace(/\s+/g, '_')}.pdf`);
  };

  const getIcon = (category) => {
    switch (category) {
      case 'Lab Result': return FileText;
      case 'Radiology': return Activity;
      case 'Prescription': return FileText;
      default: return Users;
    }
  };

  if (loading) return (
    <div className="flex items-center justify-center h-[60vh]">
      <div className="w-12 h-12 border-4 border-primary/20 border-t-primary rounded-full animate-spin"></div>
    </div>
  );

  if (error) return (
    <div className="flex flex-col items-center justify-center h-[60vh] text-center p-8">
      <div className="w-16 h-16 bg-red-50 text-red-500 rounded-2xl flex items-center justify-center mb-4">
        <Activity className="w-8 h-8" />
      </div>
      <h2 className="text-xl font-bold text-gray-800">Error Loading Reports</h2>
      <p className="text-gray-500 mt-2">{error}</p>
      <button 
        onClick={fetchReports}
        className="mt-6 bg-primary text-white px-6 py-2 rounded-xl font-bold shadow-lg shadow-primary/20"
      >
        Try Again
      </button>
    </div>
  );

  return (
    <div className="space-y-8">
      <header>
        <h1 className="text-3xl font-bold text-gray-800">Medical Reports</h1>
        <p className="text-gray-400 mt-1 font-medium">Analytical overview of hospital operations and patient metrics.</p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
         {reports.length > 0 ? reports.map((report, i) => {
           const Icon = getIcon(report.category);
           return (
             <div 
              key={report._id}
              className="glass-card p-8 group cursor-pointer hover:border-primary/20 transition-all"
             >
                <div className="w-14 h-14 bg-primary/5 text-primary rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                   <Icon className="w-7 h-7" />
                </div>
                <h3 className="text-lg font-bold text-gray-800 mb-1 group-hover:text-primary transition-colors">{report.title}</h3>
                <p className="text-sm font-medium text-gray-500 mb-2">Patient: {report.patient?.name}</p>
                <p className="text-xs text-gray-400 font-bold uppercase tracking-wider">
                  {new Date(report.date).toLocaleDateString()} • {report.fileSize}
                </p>
                
                <button 
                  onClick={(e) => {
                    e.stopPropagation();
                    handleDownload(report);
                  }}
                  className="mt-8 w-full flex items-center justify-center gap-2 py-3 bg-gray-50 text-gray-600 rounded-xl font-bold text-sm hover:bg-primary hover:text-white transition-all active:scale-95"
                >
                   <Download className="w-4 h-4" />
                   Download PDF
                </button>
             </div>
           );
         }) : (
           <div className="col-span-full py-20 text-center">
             <p className="text-gray-400 font-bold">No reports found.</p>
           </div>
         )}
      </div>

      {/* Analytics Card Placeholder */}
      <div className="glass-card p-10 bg-primary/5 border-primary/10">
         <div className="max-w-2xl">
            <h2 className="text-2xl font-bold text-gray-800 mb-4">Custom Report Generator</h2>
            <p className="text-gray-500 font-medium leading-relaxed">
              Need a specific dataset? Use our advanced query builder to generate custom Excel or PDF reports based on date ranges, departments, or patient demographics.
            </p>
            <button className="mt-8 bg-primary text-white px-8 py-4 rounded-2xl font-bold shadow-xl shadow-primary/20 hover:scale-105 transition-transform">
               Open Report Builder
            </button>
         </div>
      </div>
    </div>
  );
};

export default Reports;
